# Generated by Django 5.0.1 on 2024-08-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_vendor_image_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(null=True, upload_to='vendors'),
        ),
    ]
