# Generated by Django 5.0.1 on 2024-08-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_vendor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='chat_response_time',
        ),
    ]
