# Generated by Django 5.0.1 on 2024-08-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='Country',
            field=models.CharField(default='Pakistan', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.vendor'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(default="123 Queens' Rd, Saddar", max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='Karachi', max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='Sindh', max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(default='75290', max_length=200),
        ),
    ]
